In [1]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])

In [2]:
a1+a2

array([ 6,  8, 10, 12])

In [3]:
a1-a2

array([-4, -4, -4, -4])

In [4]:
a1*a2

array([ 5, 12, 21, 32])

In [5]:
a2/a1

array([5.        , 3.        , 2.33333333, 2.        ])

In [6]:
a2**a1

array([   5,   36,  343, 4096], dtype=int32)

In [7]:
a2%a1

array([0, 0, 1, 0], dtype=int32)

In [8]:
a1.dot(a2)

70

In [9]:
a1[0]

1

In [10]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a.ndim

2

In [12]:
a1.ndim

1

In [13]:
a.itemsize

4

In [14]:
a.dtype  # data type is dtype('int32')

dtype('int32')

In [15]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)  #dtype = np.float64 define float type data type
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [16]:
a.itemsize

8

In [17]:
a.dtype

dtype('float64')

In [18]:
a.size

6

In [19]:
a.shape

(3, 2)

In [20]:
a=np.array([[1,2],[3,4],[5,6]] ,dtype=np.complex)    #dtype = np.complex define data as complex
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [21]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
l=range(5)
l

range(0, 5)

In [24]:
b=np.arange(1,5)
b

array([1, 2, 3, 4])

In [25]:
np.arange(1,5,2)

array([1, 3])

In [26]:
np.arange(1,5,10)

array([1])

In [27]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
np.linspace(1,5,25)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ,
       2.66666667, 2.83333333, 3.        , 3.16666667, 3.33333333,
       3.5       , 3.66666667, 3.83333333, 4.        , 4.16666667,
       4.33333333, 4.5       , 4.66666667, 4.83333333, 5.        ])

# . ############################.

In [29]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.shape

(3, 2)

In [31]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [34]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a.min()

1

In [36]:
a.max()

6

In [37]:
a.mean()

3.5

In [38]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [39]:
a.sum()

21

In [40]:
a.sum(axis=0)

array([ 9, 12])

In [41]:
a.sum(axis=1)

array([ 3,  7, 11])

# Iterate numpy array using nditer 

In [42]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
for cell in a.flatten():
    print (cell)

0
1
4
9
16
25
36
49
64
81
100
121


In [44]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [45]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [46]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [47]:
for x in np.nditer(a,op_flags=['readwrite']):
    print (x)
    x[...]=x*x

0
1
2
3
4
5
6
7
8
9
10
11


In [48]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [49]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [50]:
for 

SyntaxError: invalid syntax (<ipython-input-50-eaf083cb72bb>, line 1)