# Indexing and slicing

In [1]:
import numpy as np

In [2]:
n=[2,3,4,5]
n

[2, 3, 4, 5]

In [3]:
n[0]

2

In [4]:
n[2:4]

[4, 5]

In [5]:
n[-2]

4

In [6]:
a=np.array([2,4,6,8])
a

array([2, 4, 6, 8])

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a[2,2]

9

In [9]:
a[0,1]

2

In [10]:
a[0:3,2]

array([3, 6, 9])

In [11]:
a[-1,0:2]

array([7, 8])

In [12]:
a[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

# Iterate through arrays

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [15]:
for i in a.flat:
    print (i)

1
2
3
4
5
6
7
8
9


# Stacking together two array

In [16]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [17]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [21]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
result=np.hsplit(a,3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [23]:
result=np.hsplit(a,5)
result

[array([[ 0,  1,  2],
        [15, 16, 17]]), array([[ 3,  4,  5],
        [18, 19, 20]]), array([[ 6,  7,  8],
        [21, 22, 23]]), array([[ 9, 10, 11],
        [24, 25, 26]]), array([[12, 13, 14],
        [27, 28, 29]])]

In [24]:
for i in range(0,5):
    print(result[i])

[[ 0  1  2]
 [15 16 17]]
[[ 3  4  5]
 [18 19 20]]
[[ 6  7  8]
 [21 22 23]]
[[ 9 10 11]
 [24 25 26]]
[[12 13 14]
 [27 28 29]]


In [25]:
ans=np.vsplit(a,2)
ans

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [26]:
ans[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [27]:
ans[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Indexing with boolean arrays

In [28]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [31]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])